# Generated by Django 6.0.4 on 2026-04-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('primary_goal', models.CharField(choices=[('general_fitness', 'General Fitness'), ('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('recomposition', 'Recomposition')], max_length=20)),
                ('body_part_priority', models.CharField(choices=[('upper_priority', 'Upper Body Priority'), ('lower_priority', 'Lower Body Priority'), ('balanced', 'Balanced'), ('chest_back_legs', 'Chest + Back + Legs'), ('legs_glutes_focus', 'Legs & Glutes Focus'), ('custom', 'Custom')], max_length=20)),
                ('training_experience_level', models.CharField(choices=[('complete_novice', 'Complete Novice'), ('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('years_of_training', models.CharField(choices=[('0', 'None'), ('0_to_1', 'Less than 1 year'), ('1_to_2', '1-2 years'), ('2_to_5', '2-5 years'), ('5_plus', '5+ years')], max_length=10)),
                ('currently_training', models.CharField(choices=[('no', 'No'), ('yes_irregularly', 'Yes, irregularly'), ('yes_regularly', 'Yes, regularly')], max_length=20)),
                ('previous_sports', models.CharField(blank=True, max_length=200)),
                ('pushups_to_failure', models.PositiveIntegerField(blank=True, null=True)),
                ('pullups_to_failure', models.PositiveIntegerField(blank=True, null=True)),
                ('bodyweight_squats_to_failure', models.PositiveIntegerField(blank=True, null=True)),
                ('days_per_week_available', models.PositiveIntegerField(choices=[(2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days')])),
                ('max_session_minutes', models.PositiveIntegerField(choices=[(45, '45 min'), (60, '60 min'), (75, '75 min'), (90, '90 min'), (120, '120 min')])),
                ('current_activity_level', models.CharField(choices=[('not_active', 'Not Active'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('active', 'Active'), ('very_active', 'Very Active')], max_length=20)),
                ('job_activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('mixed', 'Mixed'), ('physically_active', 'Physically Active'), ('physically_demanding', 'Physically Demanding')], max_length=25)),
                ('average_sleep', models.CharField(choices=[('less_than_5h', 'Less than 5h'), ('5_to_6h', '5-6h'), ('6_to_7h', '6-7h'), ('7_to_8h', '7-8h'), ('8_plus_h', '8+ h')], max_length=15)),
                ('average_stress', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=10)),
                ('current_steps', models.CharField(choices=[('less_than_3k', 'Less than 3k'), ('3k_to_5k', '3-5k'), ('5k_to_8k', '5-8k'), ('8k_to_12k', '8-12k'), ('12k_plus', '12k+')], max_length=15)),
                ('injury_history', models.CharField(choices=[('no', 'No'), ('yes_minor', 'Yes, minor'), ('yes_major', 'Yes, major')], max_length=10)),
                ('body_part_affected', models.CharField(blank=True, max_length=200)),
                ('current_pain_flags', models.CharField(choices=[('no', 'No'), ('yes_mild', 'Yes, mild'), ('yes_significant', 'Yes, significant')], max_length=20)),
                ('preferred_exercises', models.TextField(blank=True)),
                ('disliked_exercises', models.TextField(blank=True)),
                ('training_story', models.TextField(blank=True)),
                ('limitations_story', models.TextField(blank=True)),
                ('extra_notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
