# Generated by Django 6.0.4 on 2026-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intakeprofile',
            name='disliked_exercises',
        ),
        migrations.RemoveField(
            model_name='intakeprofile',
            name='preferred_exercises',
        ),
        migrations.AddField(
            model_name='intakeprofile',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
