# Generated by Django 5.2.8 on 2026-04-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_remove_intakeprofile_disliked_exercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeprofile',
            name='body_part_priority',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('upper_priority', 'Upper Body Priority'), ('lower_priority', 'Lower Body Priority')], max_length=20),
        ),
    ]
