# Generated by Django 6.0.4 on 2026-04-12 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('template_key', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlannedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=20)),
                ('movement_category', models.CharField(max_length=40)),
                ('sets', models.PositiveIntegerField()),
                ('reps_min', models.PositiveIntegerField()),
                ('reps_max', models.PositiveIntegerField()),
                ('target_rpe', models.PositiveIntegerField()),
                ('rest', models.CharField(max_length=20)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='plans.plannedsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('split_type', models.CharField(max_length=40)),
                ('days_per_week', models.PositiveIntegerField()),
                ('max_session_minutes', models.PositiveIntegerField()),
                ('volume_targets', models.JSONField(blank=True, null=True)),
                ('volume_actual', models.JSONField(blank=True, null=True)),
                ('validation_report', models.JSONField(blank=True, null=True)),
                ('ai_draft', models.JSONField(blank=True, null=True)),
                ('ai_refined', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plannedsession',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='plans.weeklyplan'),
        ),
    ]
