# Generated by Django 6.0.4 on 2026-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='generation_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
