# Generated by Django 5.2.8 on 2026-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_weeklyplan_generation_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedexercise',
            name='target_rpe',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
