# Generated by Django 5.2.8 on 2026-04-19 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_weeklyplan_generation_params'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('planned_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='plans.plannedsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LoggedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('planned_exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_instances', to='plans.plannedexercise')),
                ('training_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_exercises', to='logs.traininglog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LoggedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('reps_done', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rpe_done', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now=True)),
                ('logged_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='logs.loggedexercise')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('logged_exercise', 'set_number')},
            },
        ),
    ]
